# postgress / cloud9 configuration%>
# HEROKU works out of the box settings envs to:
#   USERNAME: user
#   PASSWORD:      (empty)
#   IP: localhost
#   DATABASE_NAME: app-dev

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: smc_test_ja_development

test:
  <<: *default
  database: smc_test_ja_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %> 